[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2018"

repository = "https://github.com/keylime/rust-keylime"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
